### ISSUE TITLE
Tutorial Colab File not working anymore due to Dataset or Python function changes

### ISSUE THREAD

**Issue by gefahrenquelle** [EugOT/CN-pr-Allen-Brain#1]
@EugOT 
The two Colab files you provided us dont work anymore, especially line 'stimulus_table.query('omitted').head(10)' at the "Describe stimulus Omission" session throws an error. I tried to fix the query but was unsuccessful unfortunately, could you please help us out?

Thanks!

**Comment by EugOT** [comment]
I'll check it now

**Comment by EugOT** [comment]
The problem was due to subsettina of stimulus table because 'stimulus table image name" included 'NaN" values
Therefore, query should be stimulus table.query limage name == "omitted"'). However, later we need all images + omitted for all cells across trials - to do it you should remove "NaN' from the table completely with stimulus_table = stimulus_table[stimulus_table.image_name.notna()l
I also added code for a bettter (IMHO) dimension reduction method [PaCMAP](https://github.com/YingfanWang/PaCMAP)
